package com.edc.restaurant.views;

import com.edc.restaurant.data.DataImplements;
import com.edc.restaurant.data.IData;
import com.edc.restaurant.models.Product;
import com.edc.restaurant.tools.Observable;
import com.edc.restaurant.tools.Observer;
import java.util.ArrayList;

public class MenuProductsView extends javax.swing.JPanel implements Observable, Observer {

    private ArrayList<Observer> observers;

    private ArrayList<Product> products;
    private IData data;

    public MenuProductsView() {
        observers = new ArrayList<>();

        data = new DataImplements();
        this.products = data.readData("productos.dat");

        initComponents();

        this.createProductViewComponents();
    }

    public void createProductViewComponents() {
        if (products == null) {
            return;
        }

        for (Product product : products) {
            ProductView productView = new ProductView(product);
            productView.addObservable(this);
            this.pnlProducts.add(productView);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProducts = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1000, 750));
        setLayout(new java.awt.BorderLayout());

        pnlProducts.setMinimumSize(new java.awt.Dimension(1000, 750));
        pnlProducts.setPreferredSize(new java.awt.Dimension(1000, 750));
        pnlProducts.setLayout(new java.awt.GridLayout(3, 4));
        add(pnlProducts, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlProducts;
    // End of variables declaration//GEN-END:variables
    // Inicio Observer
    @Override
    public void update(Object args) {
        notifyObservables(args);
    }

    @Override
    public void update() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    // Fin Observer

    // Inicio Observable
    @Override
    public void addObservable(Observer o) {
        this.observers.add(o);
    }

    @Override
    public void removeObservable(Observer o) {
        this.observers.remove(o);
    }

    @Override
    public void notifyObservables() {
        for (Observer observer : observers) {
            observer.update();
        }
    }

    @Override
    public void notifyObservables(Object arg) {
        for (Observer observer : observers) {
            observer.update(arg);
        }
    }
    // Fin Observable

}
